model_name_or_path: stabilityai/stable-diffusion-xl-base-1.0

output_dir: output/cooper_lora

instance_data_dir: data/instance
class_data_dir: data/reg

instance_prompt: "a photo of cooper_person"
class_prompt: "a photo of a person"

resolution: 512
train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1e-4
max_train_steps: 800
checkpointing_steps: 100

resume_from_lora: true
resume_lora_path: output/cooper_lora/pytorch_lora_weights.safetensors

rank: 8

mixed_precision: bf16
seed: 42
