model_name_or_path: stabilityai/stable-diffusion-xl-base-1.0

output_dir: output/cooper_lora

instance_data_dir: data/instance
instance_prompt: "photo of cooper_person"

resolution: 512

train_batch_size: 1
gradient_accumulation_steps: 4 

learning_rate: 5e-5
max_train_steps: 1200

rank: 16
lora_alpha: 16
lora_dropout: 0.0

resume_from_lora: true
resume_lora_path: output/cooper_lora/pytorch_lora_weights.safetensors

mixed_precision: bf16
seed: 42
