model_name_or_path: stabilityai/stable-diffusion-xl-base-1.0

output_dir: output/cooper_lora

instance_data_dir: data/instance
instance_prompt: "cooper_person"

resolution: 768

train_batch_size: 1
gradient_accumulation_steps: 4 

learning_rate: 5e-5
max_train_steps: 3000

rank: 16
lora_alpha: 16
lora_dropout: 0.05

resume_from_lora: true
resume_lora_path: output/cooper_lora/checkpoint-500

mixed_precision: bf16
seed: 42
