model_name_or_path: stabilityai/stable-diffusion-xl-base-1.0

output_dir: output/cooper_lora

instance_data_dir: data/instance
instance_prompt: "a detailed photo of cooper_person, a white man"

resolution: 1024

train_batch_size: 1
gradient_accumulation_steps: 4 

learning_rate: 2e-5
max_train_steps: 3000

rank: 32
lora_alpha: 32
lora_dropout: 0.05

resume_from_lora: true
resume_lora_path: output/cooper_lora/pytorch_lora_weights.safetensors

mixed_precision: bf16
seed: 42
